import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./component/navbar"
import Footer from "./component/footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "MyBlogPage",
	description: "Generated by ethem",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
